### ISSUE TITLE
Create "invites.list"

### ISSUE THREAD

**Issue by zstumgoren** [stanfordjournalism/stanford-progj-admin#1]
Flesh out this [inviites.list](https://github.com/stanfordjournalism/stanford-progj-admin/blob/master/tasks/invites.py#L8)

* https://developer.github.com/v3/repos/invitations/
* https://developer.github.com/v3/repos/invitations/#list-a-users-repository-invitations
* https://pygithub.readthedocs.io/en/latest/github_objects/Invitation.html

**Comment by Dilcia19** [comment]
This part is done.
