### ISSUE TITLE
Create "invites.accept"

### ISSUE THREAD

**Issue by zstumgoren** [stanfordjournalism/stanford-progj-admin#2]
Flesh out [invites.accept](https://github.com/stanfordjournalism/stanford-progj-admin/blob/master/tasks/invites.py#L18)

* https://pygithub.readthedocs.io/en/latest/github_objects/Invitation.html
* https://developer.github.com/v3/repos/invitations/
* https://developer.github.com/v3/repos/invitations/#accept-a-repository-invitation

**Comment by Dilcia19** [comment]
This part is done.
