### ISSUE TITLE
List and Accept - flesh out later

### ISSUE THREAD

**Issue by Dilcia19** [stanfordjournalism/stanford-progj-admin#3]
Hi @zstumgoren I added the list and accept function and it works.
However, when the repos get listed, they only get listed by ID. 
Thus, the accept part of the script accepts all the invites.
Also, I put everything on one piece of script, so we don't need the second task.
Accepting the invites is only 2 additional lines of code because of the listing by ID.

- [ ] This is not a huge problem, but you might want to look into it. Script should work. I just ran it and all of my invites have been accepted.

**Comment by zstumgoren** [comment]
@Dilcia19 Nice work implementing! But can we keep the `list` and `accept` tasks separate? Having the `list` task accept invites will be unexpected and confusing semantically. The `list` function is intended to be informative and should have no side effects. It's useful for administrators who get invites from numerous sources (e.g. folks who may be involved in multiple organizations and projects) and want a sense of what invites are outstanding. Meantime, it's fine for the `accept`  task to initially approve all invites. Long-term I'd like to add parameters to `accept` to support the ability to filter invites based on text patterns. This would support a workflow where we can first `list` our invites, and then either `accept` all invites (default behavior) or apply a more targeted approach based on pattern-matching.

**Comment by Dilcia19** [comment]
@zstumgoren, I understand that. The issue is that the listing function that I implemented won't help.

It lists everything by ID. for example this was my output after running the list script.

`Invitation(id=22553415)
Invitation(id=22553437)
Invitation(id=22553449)
Invitation(id=22553529)
Invitation(id=22560948)
Invitation(id=22583348)
Invitation(id=22584694)
Invitation(id=22617924)
Invitation(id=22633718)
Invitation(id=22640156)
Invitation(id=22655647)
Invitation(id=22661505)
Invitation(id=22678230)`

I can separate the script so that you can accept all the invites as well - but it doesn't exactly help you see who the collaborators and requesters are.

**Comment by Dilcia19** [comment]
I just pushed updated code that separates the listing and accepting of the invitation.

However, the accept still auto accepts all invitations. We can go over the issue tomorrow if you have time.

**Comment by zstumgoren** [comment]
@Dilcia19 Thanks for the changes. There are a few public methods on the `Invitation` instances you mention that provide more detail on each invitation. I updated the code to print the URL, as demoed below. Long-term we might want to spruce up the logging (e.g. clipping the `invitations/` path component in the URI, but this should do the trick for now. Thanks again!

```
(stanford-progj-admin) ~/code/stanford/stanford-progj-admin> invoke invites.list
https://github.com/tthibo/datakit-ap/invitations
https://github.com/tthibo/datakit-dworld/invitations
https://github.com/tthibo/datakit-gitlab/invitations
https://github.com/Dilcia19/comm-progj/invitations
https://github.com/DiPierro/csvkit/invitations
https://github.com/sarahStJepson/comm-177p-exercise-csvkit/invitations
https://github.com/rsyoh-97/csvkit-/invitations
https://github.com/joanneho14/comm-177p-exercise-csvkit/invitations
https://github.com/go4salma/comm-177p-exercise-csvkit/invitations
https://github.com/rsyoh-97/comm-177p-exercise-csvkit/invitations
https://github.com/himchanjung/comm-177p-exercise-csvkit/invitations
https://github.com/DiPierro/comm-177p-assignment-1/invitations
https://github.com/sarahStJepson/comm-177p-assignment-ondak_datakit/invitations
https://github.com/mdebutts/comm-177p-exercise-csvkit/invitations
https://github.com/carolineghisolfi/comm-177p-assignment-1/invitations
https://github.com/joanneho14/pwd/invitations
https://github.com/rsyoh-97/comm-177p-assignment-1/invitations
https://github.com/go4salma/comm-177p-assignment-1/invitations
https://github.com/seimistanford/comm-177p-exercise-csvkit2/invitations
https://github.com/himchanjung/comm-177p-assignment-1/invitations
https://github.com/marnfed/comm-177p-exercise-marnette_projects/invitations
https://github.com/tanjiahui10/comm-177p-exercise-datakit/invitations
https://github.com/rossewald/comm-177p-exercise-cvskit/invitations
https://github.com/rossewald/comm-177p-assignment-1/invitations
```
